### PR TITLE
read version from properties

### PR DESCRIPTION
**Pull request by sophiaso**
@snicoll refs issues #258 #259

### CODE REVIEW

**Comment by snicoll** [comment]
Why do you need to have access to this information?

**Comment by yungez** [comment]
version info is part of usage data that we'd like to track.

**Comment by snicoll** [comment]
It's not a blocker and feel free to merge this but have you considered using the manifest and set  the version for your root package instead? This [article is old but describes what I mean](https://www.javaworld.com/article/2074257/core-java/accessing-package-version-information-in-java-code.html)

**Comment by sophiaso** [comment]
@snicoll Thank you, I have considered using manifest, but there is some test case relying on the version number and I need the version number in test phase, will double check the test case later.

**Pull request merged**
