### PR TITLE
Update metrics starter dependency

### PR DESCRIPTION
**Pull request by dhaval24**
Addresses #451

### CODE REVIEW

**Comment by dhaval24** [comment]
@sophiaso @Incarnation-p-lee please review this PR. It is a small change to update the dependency of Micrometer API to latest stable version on maven central (1.1.0)

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
I see, something minor changes due to GA release. Could you please fix the build error ? than we can merge that.

**Comment by dhaval24** [comment]
@Incarnation-p-lee I am not sure why build is failing. When, I run mvn clean install on my machine everything passes gracefully.

**Comment by Incarnation-p-lee** [comment]
@dhaval24 
OK. may due to TravisCI network issue. Let me check it right now.

**Comment by sophiaso** [comment]
Hi @dhaval24, could you merge your branch with the latest `Microsoft/master` branch to get the log configuration updated? In order to fix the TravisCI build failure. Thanks.

**Comment by dhaval24** [comment]
@sophiaso sure, I will update this tomorrow.

**Comment by dhaval24** [comment]
@sophiaso I just merged the latest master. Please let me know if we can now merge the PR once the build passes.

**Pull request merged**
