### PR TITLE
Adding JWKSetCache Customization

### PR DESCRIPTION
**Pull request by bcannariato**
## Summary
Adding support for JWKSetCache customization

## Issue Type

- Bug fixing

## Additional Information
Related to https://github.com/microsoft/azure-spring-boot/issues/802 and https://github.com/microsoft/azure-spring-boot/pull/804

### CODE REVIEW

**Comment by neuqlz** [comment]
@bcannariato Hi, IT seems failed.  The code style check doesn't pass so the maven build failed, please refine the codes to meet the agreement of code style check. You can refer to the microsoft.azure-spring-boot details to see the details.

**Comment by bcannariato** [comment]
> @bcannariato Hi, IT seems failed. The code style check doesn't pass so the maven build failed, please refine the codes to meet the agreement of code style check. You can refer to the microsoft.azure-spring-boot details to see the details.

Can you tell me what the errors with checkstyle are? It says you can re-run in the build to get proper logs for it.

**Comment by bcannariato** [comment]
@neuqlz can we chat tonight potentially, I see you are in China so our timezones don't line up. I can be on around 9 PM CST which should be 11 AM your time I believe. Hopefully we can work together to debug these build issues to get this pull request done

**Comment by Incarnation-p-lee** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Microsoft/azure-spring-boot/pullRequest?prid=4953326&bid=16370004)

**Comment by neuqlz** [comment]
Hi @bcannariato 
Sorry I have a meeting at 11 AM. But doesn't matter. I can solve the problem for you. ^_^
It seems that there needs my reply: /azp run to run the IT pipeline every time. So it is difficult for you to see the build error logs. As you said, because of the different time zone and IT pipeline running conditions, that will take too much extra effort for you to solve it. That is unnecessary. The errors are just like: some line is too long etc. It pretty easy to solve. So I will merge it into the master and then I solve it by myself.

**Pull request merged**
